ci:
  collect:
    staticDistDir: ./dist/client
    url:
      - http://localhost/
      - http://localhost/blog/
      - http://localhost/biography/
    numberOfRuns: 1
  upload:
    target: temporary-public-storage
